
name: GitHub-Pages Deploy

on:
    pull_request:
        branches: [master]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Checking to gh-pg"
              run: |
                  git checkout gh-pages
                  git merge master
                  |
