
name: GitHub-Pages Deploy

on:
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
    steps:
        run: git checkout gh-pages
        run: git merge master

